language: python
sudo: required


python:
  - '3.6'
  - '3.5'
matrix:
  include:
    - python: '3.6'
      env: TOKIO="y"
  allow_failures:
    - env: TOKIO="y"

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -Ur requirements-dev.txt
    - python setup.py develop
    - |
        if [ "$TOKIO" = "y" ]; then
          pip install -U git+git://github.com/PyO3/tokio.git@master
        fi;

script:
    make cov
after_success:
    codecov
